### ISSUE TITLE
tomcat: ERROR (abnormal termination)

### ISSUE THREAD

**Issue by davisrixi** [seshendra/vagrant-ubuntu-tomcat7#12]
There was and error when I executed sudo supervisorctl start tomcat

**Comment by FranzSkuffka** [comment]
try vagrant provision,
if it doesnt work, destroy and re up.

**Comment by davisrixi** [comment]
Everything was ok until running the command
$ sudo supervisorctl start tomcat
![imgerror](https://cloud.githubusercontent.com/assets/7546723/5742319/27a62218-9bdf-11e4-9974-63ae641f3044.jpg)

**Comment by FranzSkuffka** [comment]
what does <code> $ supervisorctl tail tomcat </code> give you?

**Comment by davisrixi** [comment]
here you have
![tail](https://cloud.githubusercontent.com/assets/7546723/5758184/efd6c4b6-9c90-11e4-9a28-a5373f6875be.jpg)

**Comment by FranzSkuffka** [comment]
I'm afraid i can't really help you.
However, what were you going to use it for anyways? Maybe there's an alternative.

**Comment by davisrixi** [comment]
I want to implement a vm with vagrant for deploying J2EE applications. There are no many tutorials like this, so I decided to use it as a guide. I'd appreciate if you can share with me a complete configuration in vagrant and puppet (I'm a little noob in this technologies) considering these packages: java7, maven, tomcat7,mysql 5.5. Thank you in advance.

**Comment by seshendra** [comment]
You sure you have enough memory on your laptop?

Abnormal terminations happen due to lack of system resources.

**Comment by davisrixi** [comment]
Actually I have 8 gb of RAM. I have assigned 2 gb to the vm.

**Comment by gorbeia** [comment]
It is also failing for me. It happens if you edit default.pp file from a Windows machine and you insert windows style line endings. It makes tomcat start scripts fail. Please make sure that you select unix like line endings in your edidor before saving the file.
